import {type Records,validateRecords} from './records';
export type LocalState=Records & {revision:number;lastSavedAt:string;lastMachine:string;peakCount:number;readMilestone:number;jsonMilestone:number;lastImportAt?:string};
export const DB_NAME='yuu-karaoke-performance-log-v1';
async function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('recovery');};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result)};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('別のタブを閉じてください'));});}
export async function readLocal():Promise<LocalState|undefined>{const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('state'),r=tx.objectStore('state').get('current');tx.oncomplete=()=>{db.close();try{if(r.result)validateRecords(r.result);resolve(r.result)}catch(e){reject(e)}};tx.onerror=()=>{db.close();reject(tx.error)}})}
export async function initializeLocal():Promise<LocalState>{const db=await openDB();await new Promise<void>((resolve,reject)=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),r=store.get('current');r.onsuccess=()=>{if(!r.result)store.put({songs:[],tags:[],machines:[{id:1,name:'DAM精密採点Ai'},{id:2,name:'JOY分析採点AI'}],revision:0,lastSavedAt:'',lastMachine:'',peakCount:0,readMilestone:0,jsonMilestone:0},'current')};tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(tx.error)});db.close();return (await readLocal())!;}
export async function changeLocal(change:(s:LocalState)=>LocalState,recovery=false){const db=await openDB();return new Promise<LocalState>((resolve,reject)=>{const tx=db.transaction(recovery?['state','recovery']:['state'],'readwrite'),store=tx.objectStore('state'),r=store.get('current');let next:LocalState,failure:unknown;r.onsuccess=()=>{try{if(!r.result)throw Error('読込が未完了です');next=change(r.result);validateRecords(next);if(recovery)tx.objectStore('recovery').put(r.result,'before-import');store.put(next,'current')}catch(e){failure=e;tx.abort()}};tx.oncomplete=()=>{db.close();resolve(next)};tx.onabort=tx.onerror=()=>{db.close();reject(failure||tx.error)}})}
export async function saveRecords(records:Records,revision:number,lastMachine?:string){validateRecords(records);return changeLocal(s=>{if(s.revision!==revision)throw Error('別のタブで更新されました。入力を控えてから再読み込みしてください');return {...s,...records,lastMachine:lastMachine??s.lastMachine,revision:s.revision+1,peakCount:Math.max(s.peakCount,records.songs.length),lastSavedAt:new Date().toISOString()}})}
export const milestone=(s:LocalState)=>s.peakCount<150?0:Math.floor(s.peakCount/50)*50;
export async function markExport(kind:'read'|'json',revision:number){return changeLocal(s=>{if(s.revision!==revision)throw Error('出力中に記録が更新されました。もう一度出力してください');return {...s,[kind==='read'?'readMilestone':'jsonMilestone']:milestone(s)}})}
export function backupText(s:LocalState){return JSON.stringify({format:'yuu-karaoke-backup',version:1,exportedAt:new Date().toISOString(),records:{songs:s.songs,tags:s.tags,machines:s.machines},settings:{lastMachine:s.lastMachine}},null,2)}
export function parseBackup(text:string):{records:Records;lastMachine:string}{const v=JSON.parse(text);if(v.format && (v.format!=='yuu-karaoke-backup'||v.version!==1))throw Error('このバックアップの形式・バージョンには対応していません');const records=v.records??v;validateRecords(records);if(v.settings?.lastMachine!==undefined&&typeof v.settings.lastMachine!=='string')throw Error('採点機設定が不正です');return {records,lastMachine:v.settings?.lastMachine??''}}
export async function restoreRecords(data:ReturnType<typeof parseBackup>,revision:number){return changeLocal(s=>{if(s.revision!==revision)throw Error('確認中に別のタブで更新されました。再読み込みしてください');return {...s,...structuredClone(data.records),lastMachine:data.lastMachine,revision:s.revision+1,peakCount:data.records.songs.length,readMilestone:0,jsonMilestone:0,lastImportAt:new Date().toISOString(),lastSavedAt:new Date().toISOString()}},true)}
export async function recoveryBackup(){const db=await openDB();return new Promise<LocalState|undefined>((resolve,reject)=>{const tx=db.transaction('recovery'),r=tx.objectStore('recovery').get('before-import');tx.oncomplete=()=>{db.close();resolve(r.result)};tx.onerror=()=>{db.close();reject(tx.error)}})}
